import * as dotenv from 'dotenv'
import * as path from 'path'
dotenv.config({ path: path.resolve(__dirname, '..', '.env.local') })

import mongoose from 'mongoose'

const MONGODB_URI = process.env.MONGODB_URI || ''

const VerseSchema = new mongoose.Schema({
  category: { type: String, required: true, index: true },
  scripture: { type: String, required: true },
  reference: { type: String, required: true },
  declaration: { type: String, default: '' },
  commentary: { type: String, default: '' },
  active: { type: Boolean, default: true },
  created_at: { type: Date, default: Date.now },
})

const BraceletVerseHistorySchema = new mongoose.Schema({
  bracelet_code: { type: String, required: true, index: true },
  verse_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Verse', required: true },
  shown_at: { type: Date, default: Date.now },
})

const Verse = mongoose.models.Verse || mongoose.model('Verse', VerseSchema)
const BraceletVerseHistory = mongoose.models.BraceletVerseHistory || mongoose.model('BraceletVerseHistory', BraceletVerseHistorySchema)

const identityVerses = [
  { scripture: "For you created my inmost being; you knit me together in my mother's womb. I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.", reference: "Psalm 139:13-14 (NIV)", declaration: "I declare that I am fearfully and wonderfully made by God. My existence is intentional and my worth is established in Him.", commentary: "God did not create you by accident. Every detail of who you are was designed with purpose. You are not a mistake — you are a masterpiece." },
  { scripture: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.", reference: "John 1:12 (NIV)", declaration: "I declare that I am a child of God, fully adopted into His family with all rights and privileges.", commentary: "Your identity is not defined by your past, your failures, or what others say. Your identity is sealed by what God has declared over you." },
  { scripture: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.", reference: "1 Peter 2:9 (NIV)", declaration: "I declare that I am chosen, royal, holy, and God's special possession. I was called out of darkness for a divine purpose.", commentary: "You are not ordinary. God has placed a royal calling on your life. Walk today with the confidence of someone who belongs to the King." },
  { scripture: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", reference: "Ephesians 2:10 (NIV)", declaration: "I declare that I am God's masterpiece, created for good works that He has already prepared for me.", commentary: "Before you were born, God had assignments ready for you. You carry purpose in your DNA. Don't shrink from it — walk in it." },
  { scripture: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.", reference: "Galatians 2:20 (NIV)", declaration: "I declare that Christ lives in me and I walk by faith, not by sight. My old identity is gone; I am new in Him.", commentary: "The person you used to be no longer has authority over you. You are now defined by Christ's resurrection power living inside you." },
  { scripture: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", reference: "2 Corinthians 5:17 (NIV)", declaration: "I declare that I am a brand new creation in Christ. The old me is gone — I walk in the newness of who God says I am.", commentary: "Your history does not define your destiny. The moment you came to Christ, a divine reset happened. You are genuinely new." },
  { scripture: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!", reference: "1 John 3:1 (NIV)", declaration: "I declare that I am deeply loved by the Father and fully accepted as His child.", commentary: "This is not a future promise — it is a present reality. You are a child of God right now, in this moment, exactly as you are." },
  { scripture: "Before I formed you in the womb I knew you, before you were born I set you apart; I appointed you as a prophet to the nations.", reference: "Jeremiah 1:5 (NIV)", declaration: "I declare that God knew me before I was born and set me apart for His purposes.", commentary: "Your calling preceded your birth. God's knowledge of you is not shallow — He formed you knowing your full story, and called you anyway." },
  { scripture: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.", reference: "Zephaniah 3:17 (NIV)", declaration: "I declare that God delights in me and rejoices over me with singing. I am His delight.", commentary: "Imagine God singing over you. That is not metaphor — that is theology. He is not merely tolerating you; He is celebrating you." },
  { scripture: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", reference: "Romans 8:28 (NIV)", declaration: "I declare that everything in my life is working together for my good because I am called according to God's purpose.", commentary: "Your trials are not testimonies of abandonment. They are pieces of a story God is weaving into something glorious." },
  { scripture: "I can do all this through him who gives me strength.", reference: "Philippians 4:13 (NIV)", declaration: "I declare that I can do all things through Christ who strengthens me. I am not limited by my own ability.", commentary: "Your capability is not determined by your own resources. When Christ is your source, impossible becomes possible." },
  { scripture: "The Spirit you received does not make you slaves, so that you live in fear again; rather, the Spirit you received brought about your adoption to sonship. And by him we cry, 'Abba, Father.'", reference: "Romans 8:15 (NIV)", declaration: "I declare that I have received the spirit of adoption. I approach God as my Father with confidence and love.", commentary: "You have not been given a spirit of timidity or slavery. You carry the Spirit of sonship — you belong completely to the Father." },
  { scripture: "But the Lord said to Samuel, 'Do not consider his appearance or his height, for I have rejected him. The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.'", reference: "1 Samuel 16:7 (NIV)", declaration: "I declare that God sees my heart, not my appearance. I am valued for who I am, not how I look.", commentary: "The world judges by what it sees. God judges by what He knows. He sees the real you — and He chose you anyway." },
  { scripture: "For you did not receive a spirit that makes you a slave again to fear, but you received the Spirit of sonship.", reference: "Romans 8:15 (NIV)", declaration: "I declare that fear has no authority over me. I walk in the spirit of God's son/daughter.", commentary: "Fear is not your identity. Courage is. You carry the Spirit of the God who conquered death — walk like it." },
  { scripture: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7 (NIV)", declaration: "I declare that God cares deeply for me and I release all anxiety into His capable hands.", commentary: "You were never meant to carry the weight of the world. God's invitation is clear: give it to Him. He can handle what you cannot." },
  { scripture: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", reference: "Philippians 1:6 (NIV)", declaration: "I declare that God is still working in me and He will not stop until His perfect work is complete.", commentary: "You are not a finished product yet. God is still sculpting you. The fact that He started means He intends to finish." },
]

const healingVerses = [
  { scripture: "He himself bore our sins in his body on the cross, so that we might die to sins and live for righteousness; by his wounds you have been healed.", reference: "1 Peter 2:24 (NIV)", declaration: "I declare that by the wounds of Jesus Christ, I am healed — spirit, soul, and body.", commentary: "Healing is not just physical; it is total restoration. Jesus bore your sickness so that you do not have to carry it alone." },
  { scripture: "Praise the Lord, my soul, and forget not all his benefits — who forgives all your sins and heals all your diseases.", reference: "Psalm 103:2-3 (NIV)", declaration: "I declare that the Lord heals all my diseases and forgives all my sins. I will praise Him for every benefit He provides.", commentary: "Healing is listed alongside forgiveness as one of God's benefits. What God has provided, do not forget to receive." },
  { scripture: "He heals the brokenhearted and binds up their wounds.", reference: "Psalm 147:3 (NIV)", declaration: "I declare that God is healing my broken heart and binding up every wound in my life.", commentary: "Emotional pain is not invisible to God. He is the healer of heartbreak, the restorer of shattered pieces." },
  { scripture: "Is anyone among you sick? Let them call the elders of the church to pray over them and anoint them with oil in the name of the Lord. And the prayer offered in faith will make the sick person well.", reference: "James 5:14-15 (NIV)", declaration: "I declare that prayer offered in faith produces healing. I stand on the Word and believe for my healing.", commentary: "God established healing prayer in the church for a reason. Faith-filled prayer is not passive hoping — it is active believing." },
  { scripture: "The Lord sustains them on their sickbed and restores them from their bed of illness.", reference: "Psalm 41:3 (NIV)", declaration: "I declare that the Lord sustains me and restores me to complete health.", commentary: "When you are too weak to stand, God is the One sustaining you. He does not abandon His children in seasons of sickness." },
  { scripture: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28 (NIV)", declaration: "I declare that I come to Jesus and receive His rest — rest for my body, mind, and spirit.", commentary: "Weariness is real. But so is God's rest. You do not have to be strong in your own strength when you have access to His." },
  { scripture: "He sent out his word and healed them; he rescued them from the grave.", reference: "Psalm 107:20 (NIV)", declaration: "I declare that God's Word is active in my life right now, bringing healing and rescuing me from destruction.", commentary: "God's Word is not just ink on paper. It is living, active, and capable of healing the human body and soul." },
  { scripture: "And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.", reference: "James 5:15 (NIV)", declaration: "I declare that the prayer of faith is working in my life. I am being raised up and made whole.", commentary: "Faith and healing are deeply connected. When you believe beyond what you see, you activate the divine healing process." },
  { scripture: "O Lord my God, I called to you for help, and you healed me.", reference: "Psalm 30:2 (NIV)", declaration: "I declare that I have called on the Lord and He answers me with healing and restoration.", commentary: "This is both a testimony and a promise. What God has done before, He will do again. Call on Him — He answers." },
  { scripture: "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.", reference: "Isaiah 53:5 (NIV)", declaration: "I declare that Jesus took every sickness, every pain, and every infirmity upon Himself so I can walk in complete wholeness.", commentary: "Healing was purchased 2,000 years ago on the cross. It is already paid for. Your job is to receive what He has already provided." },
  { scripture: "Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted.", reference: "Isaiah 53:4 (NIV)", declaration: "I declare that Jesus already carried my pain and suffering. I do not carry what He has already borne.", commentary: "You were never meant to carry your sickness alone. Jesus stepped into your pain so that you could walk in His health." },
  { scripture: "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well.", reference: "3 John 1:2 (NIV)", declaration: "I declare that it is God's will for me to be healthy and whole in every area of my life.", commentary: "God's will for you is wholeness — not just spiritual, but physical and emotional. Receive this prayer as God's word over your life." },
  { scripture: "Jesus reached out his hand and touched the man. 'I am willing,' he said. 'Be clean!' Immediately he was cleansed of his leprosy.", reference: "Matthew 8:3 (NIV)", declaration: "I declare that Jesus is willing to heal me. His willingness and His power are both available to me today.", commentary: "Jesus never turned away anyone who came to Him for healing. His answer to you today is the same: 'I am willing.'" },
  { scripture: "When Jesus heard this, he said, 'This illness is not to end in death. No, it is for God's glory so that God's Son may be glorified through it.'", reference: "John 11:4 (NIV)", declaration: "I declare that my sickness will not end in defeat. God will be glorified through my healing testimony.", commentary: "What looks like the end of your story is often just the setup for your miracle. God's glory is coming through your situation." },
  { scripture: "Jesus went throughout Galilee, teaching in their synagogues, proclaiming the good news of the kingdom, and healing every disease and sickness among the people.", reference: "Matthew 4:23 (NIV)", declaration: "I declare that the same Jesus who healed every disease is still healing today, and He heals me now.", commentary: "Jesus' healing ministry was comprehensive. Not some diseases — every disease. That includes yours." },
  { scripture: "He said, 'If you listen carefully to the Lord your God and do what is right in his eyes, if you pay attention to his commands and keep all his decrees, I will not bring on you any of the diseases I brought on the Egyptians, for I am the Lord, who heals you.'", reference: "Exodus 15:26 (NIV)", declaration: "I declare that the Lord is Jehovah Rapha — my Healer. Healing is part of His name and His nature.", commentary: "God's very name includes healing. This is not an occasional activity for Him — it is who He fundamentally is." },
]

const noFearVerses = [
  { scripture: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", reference: "2 Timothy 1:7 (NIV)", declaration: "I declare that I have not been given a spirit of fear. I walk in power, love, and a sound mind.", commentary: "Fear is not from God. Any spirit of timidity or anxiety does not belong to you. You carry power, love, and self-discipline instead." },
  { scripture: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", reference: "Joshua 1:9 (NIV)", declaration: "I declare that I am strong and courageous. God is with me wherever I go, so I have nothing to fear.", commentary: "God did not just say be courageous — He commanded it. That command comes with a promise: He will be with you. That changes everything." },
  { scripture: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", reference: "Psalm 23:4 (NIV)", declaration: "I declare that even in my darkest seasons, I fear no evil. God is with me and His comfort surrounds me.", commentary: "The valley does not mean God has left. It means you are walking through it, not living in it. He is your companion in every dark place." },
  { scripture: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.", reference: "Isaiah 41:10 (NIV)", declaration: "I declare that I am not afraid. God is my strength, my help, and my support. He upholds me with His powerful hand.", commentary: "This verse contains five divine promises: God is with you, He is your God, He strengthens you, He helps you, and He upholds you. You are completely covered." },
  { scripture: "The Lord is my light and my salvation — whom shall I fear? The Lord is the stronghold of my life — of whom shall I be afraid?", reference: "Psalm 27:1 (NIV)", declaration: "I declare that the Lord is my light and salvation. I will not fear any person, situation, or circumstance.", commentary: "When God is your light, darkness cannot overwhelm you. When He is your stronghold, no enemy can breach your walls." },
  { scripture: "There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.", reference: "1 John 4:18 (NIV)", declaration: "I declare that God's perfect love drives out every trace of fear from my life. I live in love, not in fear.", commentary: "Fear and love cannot coexist at full strength. The deeper you go in God's love, the less room fear has to occupy." },
  { scripture: "When I am afraid, I put my trust in you. In God, whose word I praise — in God I trust and am not afraid. What can mere mortals do to me?", reference: "Psalm 56:3-4 (NIV)", declaration: "I declare that when fear arises, I choose to trust God. His Word is my anchor and my confidence.", commentary: "Notice: David says when I am afraid — not if. Fear is a real human experience. The response is not denial; it is trust." },
  { scripture: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", reference: "Philippians 4:6 (NIV)", declaration: "I declare that I am not anxious. I bring every concern to God in prayer and trust Him with the outcomes.", commentary: "Anxiety transfers your energy into worrying. Prayer transfers your worry into God's hands. The exchange is always worth it." },
  { scripture: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", reference: "Philippians 4:7 (NIV)", declaration: "I declare that the peace of God guards my heart and mind. I am at peace, even when I do not understand everything.", commentary: "This peace is not logical — it transcends understanding. You can be perfectly peaceful in an imperfect situation because God is guarding your mind." },
  { scripture: "The Lord is my shepherd, I lack nothing.", reference: "Psalm 23:1 (NIV)", declaration: "I declare that the Lord is my shepherd and I have everything I need. I will not live in a spirit of lack or fear.", commentary: "The person who has God as their shepherd lacks nothing. That is not a feeling — it is a theological fact." },
  { scripture: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", reference: "Joshua 1:9 (NIV)", declaration: "I declare that strength and courage are my portion. I move forward without fear because God goes before me.", commentary: "This was God's word to Joshua stepping into the unknown. It is God's word to you today as you face your own unknowns." },
  { scripture: "God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea.", reference: "Psalm 46:1-2 (NIV)", declaration: "I declare that God is my refuge and strength. Even if everything around me shakes, I will not fear because He is present.", commentary: "Extreme imagery is used here on purpose. Even in the most catastrophic circumstances imaginable, fear is not the appropriate response for those who trust God." },
  { scripture: "I sought the Lord, and he answered me; he delivered me from all my fears.", reference: "Psalm 34:4 (NIV)", declaration: "I declare that as I seek God, He delivers me from every fear that tries to grip my heart.", commentary: "Deliverance from fear is not a one-time event for some — it is a repeatable promise for all who seek Him. Seek and you will find freedom." },
  { scripture: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", reference: "John 14:27 (NIV)", declaration: "I declare that I receive the peace of Jesus. My heart is not troubled and I am not afraid.", commentary: "Jesus gave you His own peace — not the fragile peace the world offers, but the unshakeable peace that He carries. It is yours." },
  { scripture: "The Lord himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged.", reference: "Deuteronomy 31:8 (NIV)", declaration: "I declare that God goes before me into every situation. I am never alone, and I will not be afraid.", commentary: "God does not send you into battles alone. He goes first. The ground you step on has already been touched by His presence." },
  { scripture: "Are not five sparrows sold for two pennies? Yet not one of them is forgotten by God. Indeed, the very hairs of your head are all numbered. Don't be afraid; you are worth more than many sparrows.", reference: "Luke 12:6-7 (NIV)", declaration: "I declare that I am highly valued by God. He knows every detail of my life and I do not need to be afraid.", commentary: "If God tracks sparrows, He certainly tracks you. Your fears are not invisible to Him. Your life is not forgotten by Him." },
]

const kidsVerses = [
  { scripture: "God loved the world so much that he gave his one and only Son. Anyone who believes in him will not die but will have eternal life.", reference: "John 3:16 (NLT)", declaration: "I know that God loves me so much He sent Jesus just for me!", commentary: "God's love for you is so big that He gave up what was most precious to Him. That's how important you are to God." },
  { scripture: "I can do everything through Christ, who gives me strength.", reference: "Philippians 4:13 (NLT)", declaration: "I declare that with Jesus helping me, I can do anything!", commentary: "When something feels too hard, remember: you're not doing it alone. Jesus is right there giving you the strength you need." },
  { scripture: "For I know the plans I have for you, says the Lord. They are plans for good and not for disaster, to give you a future and a hope.", reference: "Jeremiah 29:11 (NLT)", declaration: "I declare that God has amazing plans for my life — plans to help me, not hurt me!", commentary: "God has already been thinking about your future, and it's a good one. You can trust that He has great things planned for you." },
  { scripture: "Don't be afraid, for I am with you. Don't be discouraged, for I am your God. I will strengthen you and help you.", reference: "Isaiah 41:10 (NLT)", declaration: "I am not afraid because God is always with me and He gives me His strength!", commentary: "Whenever you feel scared, remember God promises to be right beside you, giving you courage and help." },
  { scripture: "The Lord is my shepherd; I have all that I need.", reference: "Psalm 23:1 (NLT)", declaration: "I declare that God takes care of me like a good shepherd. I have everything I need!", commentary: "A shepherd protects, guides, and provides for his sheep. God does all of that for you — every single day." },
  { scripture: "Children are a gift from the Lord; they are a reward from him.", reference: "Psalm 127:3 (NLT)", declaration: "I declare that I am a gift from God — special and precious to Him and to my family!", commentary: "You are not here by accident. God placed you in your family as a precious gift. You are loved and you belong." },
  { scripture: "Even before he made the world, God loved us and chose us in Christ to be holy and without fault in his eyes.", reference: "Ephesians 1:4 (NLT)", declaration: "I declare that God chose me before the world was even made. I am special to Him!", commentary: "Before planets, stars, or oceans existed, God was already thinking about you and choosing you. That's how loved you are." },
  { scripture: "You are the light of the world—like a city on a hilltop that cannot be hidden.", reference: "Matthew 5:14 (NLT)", declaration: "I declare that I am a light in the world. God shines through me every day!", commentary: "God put a special light inside you — kindness, joy, love. When you show those things, you light up the room." },
  { scripture: "Trust in the Lord with all your heart; do not depend on your own understanding.", reference: "Proverbs 3:5 (NLT)", declaration: "I choose to trust God with my whole heart, even when I don't understand everything!", commentary: "Sometimes life is confusing. But God always knows exactly what's happening and what to do. You can trust Him completely." },
  { scripture: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", reference: "Philippians 4:19 (NLT)", declaration: "I declare that God will take care of everything I need — He always provides for me!", commentary: "God knows every single thing you need, and He has more than enough to provide it. His supply never runs out." },
  { scripture: "God has not given us a spirit of fear and timidity, but of power, love, and self-discipline.", reference: "2 Timothy 1:7 (NLT)", declaration: "I am not afraid! God gave me power, love, and a strong mind!", commentary: "Fear does not come from God. He gave you something much better — power to overcome, love to share, and a clear mind." },
  { scripture: "What is the price of five sparrows—two copper coins? Yet God does not forget a single one of them. And the very hairs on your head are all numbered. So don't be afraid; you are more valuable to God than a whole flock of sparrows.", reference: "Luke 12:6-7 (NLT)", declaration: "I declare that I am very valuable to God. He knows everything about me and cares for me!", commentary: "If God pays attention to little birds, imagine how much He pays attention to you. You are so much more precious than you know." },
  { scripture: "See how very much our Father loves us, for he calls us his children, and that is what we are!", reference: "1 John 3:1 (NLT)", declaration: "I am God's child! He loves me with the biggest love there is!", commentary: "The Creator of the whole universe calls YOU His child. That's the most amazing title you could ever have." },
  { scripture: "The Lord your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.", reference: "Zephaniah 3:17 (NLT)", declaration: "God sings songs about me because He loves me so much and is so happy I'm His!", commentary: "Imagine God singing a happy song just about you. That's how delighted He is that you belong to Him. You make God smile." },
  { scripture: "This is the day the Lord has made. We will rejoice and be glad in it.", reference: "Psalm 118:24 (NLT)", declaration: "I declare that today is a gift from God and I choose to be happy and thankful!", commentary: "Every single day is a present from God to you. Unwrap it with a grateful and joyful heart." },
  { scripture: "My God will supply all your needs from his glorious riches, which have been given to us in Christ Jesus.", reference: "Philippians 4:19 (NLT)", declaration: "God will always give me what I truly need. I trust Him to take care of me!", commentary: "God does not forget about your needs. He sees them all and His resources are unlimited. He is your perfect provider." },
]

async function main() {
  console.log('🌱 Connecting to MongoDB...')
  await mongoose.connect(MONGODB_URI)
  console.log('✅ Connected to MongoDB')

  // Clear existing data
  await BraceletVerseHistory.deleteMany({})
  await Verse.deleteMany({})
  console.log('🗑️  Cleared existing verses and history')

  // Seed all categories
  await Verse.insertMany(identityVerses.map((v) => ({ ...v, category: 'identity', active: true })))
  console.log(`✅ Seeded ${identityVerses.length} Identity verses (NIV)`)

  await Verse.insertMany(healingVerses.map((v) => ({ ...v, category: 'healing', active: true })))
  console.log(`✅ Seeded ${healingVerses.length} Healing verses (NIV)`)

  await Verse.insertMany(noFearVerses.map((v) => ({ ...v, category: 'no-fear', active: true })))
  console.log(`✅ Seeded ${noFearVerses.length} No Fear verses (NIV)`)

  await Verse.insertMany(kidsVerses.map((v) => ({ ...v, category: 'kids', active: true })))
  console.log(`✅ Seeded ${kidsVerses.length} Kids Identity verses (NLT)`)

  console.log(`\n🎉 Database seeded successfully!`)
  console.log(`Total verses: ${identityVerses.length + healingVerses.length + noFearVerses.length + kidsVerses.length}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await mongoose.disconnect()
  })
